apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: hyperon-bundle-dep
  namespace: hyperon-bundle
spec:
  selector:
    matchLabels:
      app: hyperon-bundle
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: hyperon-bundle
    spec:
      containers:
        - name: hyperon-bundle
          image: hyperon-bundle-image
          imagePullPolicy: Always
          ports:
            - containerPort: 38080
