apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: www.sb-demo.com
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: www.sb-demo.com
    http:
      paths:
      - path: /
        backend:
          serviceName: sb-demo-service
          servicePort: 8080
