apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: blog 
spec:
  selector:
    matchLabels:
      app: blog
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: blog 
    spec:
      containers:
      - name: app 
        image: docker.amoylabs.com:30500/blog:63
        ports:
        - containerPort: 8080
