
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pvc-dynamic
  annotations:
    volume.beta.kubernetes.io/storage-class: "nfs-storage"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: producer-consumer-nfs-client
spec:
  containers:
  - image: busybox
    imagePullPolicy: IfNotPresent
    name: producer
    args:
    - /bin/sh
    - -c
    - echo "Hello" > /producer_dir/hello; sleep 30000
    volumeMounts:
    - mountPath: /producer_dir
      name: shared-volume
  - image: busybox
    imagePullPolicy: IfNotPresent
    name: consumer
    args:
    - /bin/sh
    - -c
    - cat /consumer_dir/hello; sleep 30000
    volumeMounts:
    - mountPath: /consumer_dir
      name: shared-volume
  volumes:
  - name: shared-volume
    persistentVolumeClaim:
      claimName: nfs-pvc-dynamic