apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- deployment.yaml
- service.yaml
- ingress.yaml
namespace: drools
images:
- name: drools-workbench-showcase-image
  newName: jboss/drools-workbench-showcase
  newTag: latest
