apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: drools
  name: drools-workbench-showcase-pvc
  labels:
    app: drools-workbench-showcase
  annotations:
    volume.beta.kubernetes.io/storage-class: "nfs-storage"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi