---
apiVersion: v1
kind: Namespace
metadata:
  name: docker-registry-ui
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-registry-ui
  namespace: docker-registry-ui
  labels:
    app: registry-ui
    release: docker-registry-ui
    app/version: "2.0.0"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: registry-ui
      release: docker-registry-ui
  template:
    metadata:
      labels:
        app: registry-ui
        release: docker-registry-ui
    spec:
      containers:
        - name: registry-ui
          image: "joxit/docker-registry-ui:latest"
          imagePullPolicy: IfNotPresent
          env:
            - name: REGISTRY_TITLE
              value: "Docker registry UI"
            - name: NGINX_PROXY_PASS_URL
              value: "http://docker.amoylabs.com:30500"
            - name: PULL_URL
              value: "docker.amoylabs.com:30500"
            - name: SINGLE_REGISTRY
              value: "true"
            - name: DELETE_IMAGES
              value: "true"
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {}
---
apiVersion: v1
kind: Service
metadata:
  name: docker-registry-ui
  namespace: docker-registry-ui
  labels:
    app: registry-ui
    release: docker-registry-ui
    app/version: "2.0.0"
spec:
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
      app: registry-ui
      release: docker-registry-ui
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: docker-registry-ui
  namespace: docker-registry-ui
spec:
  ingressClassName: nginx
  rules:
  - host: docker.amoylabs.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: docker-registry-ui
            port: 
              number: 80