apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- deployment.yaml
- service.yaml
- ingress.yaml
namespace: kie-server
images:
- name: kie-server-image
  newName: jboss/kie-server
  newTag: latest
