apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: www-dep 
spec:
  selector:
    matchLabels:
      app: www-app
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: www-app
    spec:
      containers:
      - name: www-springboot
        image: registry.cn-hangzhou.aliyuncs.com/guuuuo/springboot-demo:0.12	
        ports:
        - containerPort: 9080
        env:
        - name: MY_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
