apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: backoffice-dep 
spec:
  selector:
    matchLabels:
      app: backoffice-app
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: backoffice-app
    spec:
      containers:
      - name: backoffice-springboot
        image: amoylabs/backoffice:release-v0.0.1
        imagePullPolicy: Always
        ports:
        - containerPort: 9080
        env:
        - name: MY_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
