apiVersion: v1
kind: Service
metadata:
  name: backoffice-mysql
  labels:
    app: backoffice-mysql
spec:
  ports:
    - port: 3306
  selector:
    app: backoffice-mysql
    tier: mysql
  clusterIP: None
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backoffice-mysql-pv-claim
  labels:
    app: backoffice-mysql
  annotations:
    volume.beta.kubernetes.io/storage-class: "nfs-storage"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: backoffice-mysql
  labels:
    app: backoffice-mysql
spec:
  selector:
    matchLabels:
      app: backoffice-mysql
      tier: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: backoffice-mysql
        tier: mysql
    spec:
      containers:
      - image: mysql:5.6
        name: backoffice-mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: password
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: backoffice-mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: backoffice-mysql-persistent-storage
        persistentVolumeClaim:
          claimName: backoffice-mysql-pv-claim
