apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: maven
  namespace: jenkins
  annotations:
    volume.beta.kubernetes.io/storage-class: "nfs-storage"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi