apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: hyperon-studio-dep
  namespace: hyperon-studio
spec:
  selector:
    matchLabels:
      app: hyperon-studio
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: hyperon-studio
    spec:
      containers:
        - name: hyperon-studio
          image: hyperon-studio-image
          imagePullPolicy: Always
          ports:
            - containerPort: 38080
