---
apiVersion: v1
kind: Namespace
metadata:
  name: registry-ui
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: registry-ui
  namespace: registry-ui
  labels:
    app: registry-ui
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: registry-ui
  template:
    metadata:
      labels:
        app: registry-ui
    spec:
      containers:
        - name: registry-ui
          image: "joxit/docker-registry-ui:latest"
          imagePullPolicy: IfNotPresent
          env:
            - name: REGISTRY_TITLE
              value: "AmoyLabs Container Registry"
            - name: NGINX_PROXY_PASS_URL
              value: "http://cr.amoylabs.com:30500"
            - name: PULL_URL
              value: "cr.amoylabs.com:30500"
            - name: SINGLE_REGISTRY
              value: "true"
            - name: DELETE_IMAGES
              value: "true"
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {}
---
apiVersion: v1
kind: Service
metadata:
  name: registry-ui
  namespace: registry-ui
  labels:
    app: registry-ui
spec:
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
      app: registry-ui
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: registry-ui
  namespace: registry-ui
spec:
  ingressClassName: nginx
  rules:
  - host: cr.amoylabs.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: registry-ui
            port: 
              number: 80